### ISSUE TITLE
Problem with testing one-sided 

### ISSUE THREAD

**Issue by Freeklinders** [lrkrol/permutationTest#2]
Hi, 
I am trying to run a permutation test using the PermutationTest function (a great help, thanks a lot!), however, I run into a problem when trying to do it one-sided. 
 
**Code:**
[results_RC_organization_MS(1,i),results_RC_organization_MS(2,i),results_RC_organization_MS(3,i)]=permutationTest(sample1,sample2,10000,'sidedness', smaller);

**Error:**
Unrecognized function or variable 'smaller'.

When leaving out the sidedness it works (but then it tests two-sided as default). 

Thanks a lot in advance!

**Comment by lrkrol** [comment]
Hi Freek, the argument value itself should be a string, in quotes, like so:

```matlab
permutationTest(sample1, sample2, 10000, 'sidedness', 'smaller');
```

**Comment by Freeklinders** [comment]
Hi Laurens,

Just after posting the question I figured it out indeed, thanks a lot!
Cheers,
Freek
